import Head from "next/head";
import Image from "next/image";
import Sidebar from "../component/Sidebar";

export default function Home() {
  return (
    <div className="index_outerdiv">
      <Head>
        <title>Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Sidebar />
      </main>
    </div>
  );
}
